// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAkhbsEDoBBDGOuZbfZdL0armkrG2VMVY',
    appId: '1:789720923972:web:90b99af021477a768ba111',
    messagingSenderId: '789720923972',
    projectId: 'full-app-aaa58',
    authDomain: 'full-app-aaa58.firebaseapp.com',
    storageBucket: 'full-app-aaa58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcD0UlE8jGnzW3XaPjCS8RA6crHx0zQHU',
    appId: '1:789720923972:android:f6b5edb5649d1fd98ba111',
    messagingSenderId: '789720923972',
    projectId: 'full-app-aaa58',
    storageBucket: 'full-app-aaa58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0LBjCTFyEWygP09m-ZDid2FI6tWIWfU',
    appId: '1:789720923972:ios:684d2b7baba5208b8ba111',
    messagingSenderId: '789720923972',
    projectId: 'full-app-aaa58',
    storageBucket: 'full-app-aaa58.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
